### PR TITLE
PREPARE DATA: Test for load method

### PR DESCRIPTION
**Pull request by kimdiep**
Add test for load method on prepare_data.py
Solution is testing the return type is list

Suggested future enhancements:
- Ways to mock the files instead of hard-loading the .npy files into testing?

### CODE REVIEW

**Comment by kimdiep** [comment]
Initial solution:
Add test for load method on prepare_data.py using the data files, but not available to travis
Solution is testing the return type is list

Second commit:
Test for load method through provision of test.npy file for Travis CI

Suggested future enhancements:
Ways to mock the files instead of hard-loading the .npy files into testing?

**Comment by kimdiep** [comment]
I haven't found a smaller .npy file for this

**Comment by amyj0rdan** [comment]
[[MED] Feature testing: Setup Capybara/Pytest for FE / other solutions](https://trello.com/c/6X7OCfsY/90-med-feature-testing-setup-capybara-pytest-for-fe-other-solutions)

**Comment by amyj0rdan** [comment]
[Testing for prepare_data.py [MEDIUM]](https://trello.com/c/PmBE3ceg/63-testing-for-preparedatapy-medium)

**Comment by amyj0rdan** [comment]
[[HIGH] Backend refactoring for use beyond shapes / magic numbers /constants](https://trello.com/c/NgrsBsPt/96-high-backend-refactoring-for-use-beyond-shapes-magic-numbers-constants)

**Comment by amyj0rdan** [comment]
[[HIGH] Pytest: Increase test coverage - prepare_data.py](https://trello.com/c/zYBIzH6J/89-high-pytest-increase-test-coverage-preparedatapy)

**Pull request merged**
